firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from lab_4.views import home as homes
urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab_4/', include('lab_4.urls', namespace='lab_4')),
    path('',homes, name='home')
]

lab_4/urls.py
from django.urls import re_path

from .views import hello, home, message, saveproject, project_table, delete_table

app_name= 'lab_4'
urlpatterns = [
     re_path(r'^$', home, name='home'),
     re_path(r'^hello', hello, name='hello'),
     re_path(r'^message', message, name='message'),
     re_path(r'^saveproject', saveproject, name='saveproject'),
     re_path(r'^project_table', project_table, name='project_table'),
     re_path(r'^delete_table', delete_table, name='delete_table')
]

lab_4/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

# Create your models here.
class Appointment(models.Model):
    title = models.CharField(max_length=200, null=True)
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    day = models.CharField(max_length=30, null=True)
    place = models.CharField(max_length=200, null=True)
    category = models.CharField(max_length=30, null=True)

lab_4/forms.py
from django import forms
from .models import Appointment

class Add_Project_Form(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    date_attrs = {
        'type':'date',
        'class':'form-group col-xl-12',
        'placeholder':'date',
    }
    title_attrs = {
        'type': 'text',
        'class': 'form-group col-xl-12',
        'placeholder':'Title'
    }
    day_attrs = {
        'type': 'text',
        'class': 'form-group col-xl-12',
        'placeholder':'Day'
    }
    place_attrs = {
        'type': 'text',
        'class': 'form-group col-xl-12',
        'placeholder':'Place'
    }

    category_attrs = {
        'type': 'text',
        'class': 'form-group col-xl-12',
        'placeholder':'Category'
    }

    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'form-group col-xl-12',
        'placeholder':'Description'
    }

    title = forms.CharField(label='Title', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    created_date = forms.DateTimeField(label='Date', required=True, widget=forms.DateTimeInput(attrs=date_attrs))
    day = forms.CharField(label='Day', required=True, max_length=20, widget=forms.TextInput(attrs=day_attrs))
    place = forms.CharField(label='Place', required=True, max_length=200, widget=forms.TextInput(attrs=place_attrs))
    category = forms.CharField(label='Category', required=True, max_length=200, widget=forms.TextInput(attrs=category_attrs))
    desc = forms.CharField(label='Description', required=True, widget=forms.Textarea(attrs=description_attrs))

lab_4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Appointment
from .forms import Add_Project_Form

response = {}

def home(request):
    return render (request, 'index.html')

def hello(request):
    return render (request, 'sayhello.html')

def message(request):
    return render (request, 'register.html')

def saveproject(request):
    form = Add_Project_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        schedule = Appointment()
        schedule.title = form.cleaned_data['title']
        schedule.desc = form.cleaned_data['desc']
        schedule.created_date = form.cleaned_data['created_date']
        schedule.day = form.cleaned_data['day']
        schedule.place = form.cleaned_data['place']
        schedule.category = form.cleaned_data['category']
        schedule.save()
        html = 'formJadwal.html'
        return redirect('lab_4:project_table')

    else:
        form = Add_Project_Form()
        response = {'form' : form}
        return render(request, 'formJadwal.html', response)

def project_table(request):
    project = Appointment.objects.all()
    html = 'listJadwal.html'
    return render(request, html, {'project': project})

def delete_table(request):
    Appointment.objects.all().delete()
    project = Appointment.objects.all()
    html = 'listJadwal.html'
    return render(request, html, {'project': project})


# Create your views here.

lab_4/templates/formJadwal.html
{% extends "temp.html" %}
{% load static %}

{% block title %}
<title>Irfan | Create Schedule </title>
{% endblock %}

{%block content %}
    <!-- ini navbar -->
    <nav class="navbar navbar-light bg-transparent">
      <div class = "container">
        <a class="navbar-brand" href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/download.png" %}" width="50" height="50" alt="">
        </a>
        <a href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/close.png" %}" width="50" height="50" alt="">
        </a>
      </div>
    </nav>
    <!-- akhir dari navbar -->

    <!-- last jumbotron -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
          <h1 class="display-4 text-center">Create Schedule!</h1>
        </div>
      </div>
    </section>
    <!-- akhir jumbotron -->

    <!-- ini start form -->
    <section class="form">
      <div class="container">
        <form id="form" method="POST" action='{% url 'lab_4:saveproject' %}'>
          <div class="form-row">
            <div class="form-group col-md-offset-6 text">
	        	      {% csrf_token %}
	                {{ form }}
	        	<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            </div>
          </div>
        </form>
      </div>
    </section>
    <!-- ini akhir form -->

    <!-- ini waste of space -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
        </div>
      </div>
    </section>
    <!-- ini akhir waste of space -->


{% endblock %}

lab_4/templates/index.html
{% extends "temp.html" %}
{% load static %}

{% block title %}
<title>Irfan | Designer, Front-end, and Photographer </title>
{% endblock %}

{%block content %}
  <!-- ini navbar -->
  <nav class="navbar navbar-light bg-transparent">
    <div class = "container">
      <a class="navbar-brand" href='{% url 'lab_4:home' %}'>
        <img src="{% static "img/download.png" %}" width="50" height="50" alt="">
      </a>
      <a href='{% url 'lab_4:saveproject' %}'>
        <button type="button" class="btn btn-outline-warning btn-sm">Create Schedule</button>
      </a>
      <a href='{% url 'lab_4:project_table' %}'>
        <button type="button" class="btn btn-outline-warning btn-sm">List of Schedule</button>
      </a>
      <a href='{% url 'lab_4:hello' %}'>
        <button type="button" class="btn btn-outline-warning btn-lg">Say hello</button>
      </a>
    </div>
  </nav>
  <!-- akhir dari navbar -->

  <!-- Ini Jumbotron -->
  <div class="jumbotron">
    <br>
    <h1 class = text-center> <b> Designer, Front-end Developer & Photographer </b> </h1>
    <br>
    <h5 align="center"> I like to make beautiful code and take beautiful pictures </h5>
    <br>
    <br>
    <div class = "text-center">
      <img src="{% static "img/atomix_user2.png" %}">
    </div>
  </div>
  <!-- ini akhirnya -->

  <!-- gambar laptop -->
  <div class="container text-center">
    <img src="{% static "img/hero.png" %}" class="img-fluid" alt="Responsive image">
  </div>
  <!-- akhir gambar laptop -->

  <!-- paragraf about -->
  <section class="about" id="about">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="text-center"> Hi, I'm Irfan. Nice to meet you.</h1>
        <p class="text-center">I just recently start my journey as a designer,
          I've done remote work for school, consulted for startups,
          and collaborated with talented people to create digital
          products for both business and consumer use. In photography,
          i'm a professional with 7 years experiences.
          I've won many competition, awards, and been asked to be a judge.
          I'm quietly confident, naturally curious, and perpetually
          improving my chops. </p>
      </div>
    </div>
  </section>
  <!-- akhir dari paragraf about -->

  <!-- ini awal table -->
  <section class="Skills" id="Skills">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
          <br>
          <div class="text-center">
            <img src="{% static "img/design.png" %}"  class="text-center">
          </div>
          <p class="lead text-center" id="judul_tabel"> Designer </p>
          <br>
          <p class="text-center">I value simple structure, clean, very basic patterns, and toughtful interactions.</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> Things I enjoy designing</p>
          <p class="text text-center">UX, UI, Web, Mobile, Apps, Logos</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> Design Tools </p>
          <p class="text-center"> Balsamiq Mockups<br>Figma<br>Invision<br>Marvel<br>Pen & Paper<br>Sketch<br>Webflow<br>Zeplin</p>
        </div>
        <div class="col-xl-4">
          <br>
          <div class="text-center">
            <img src="{% static "img/coding.png" %}" class="text-center">
          </div>
          <p class="lead text-center" id="judul_tabel"> Front-end Developer </p>
          <br>
          <p class="text-center">I tend to code things from scratch, and enjoy bringing ideas to life in the browser.</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> Language i speak:</p>
          <p class="text text-center">HTML, Pug, Slim, CSS, Sass, Less</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> Dev Tools: </p>
          <p class="text-center"> Atom<br>Bitbucket<br>Bootstrap<br>Bulma<br>Codekit<br>Codepen<br>Github<br>Gitlab<br>Terminal </p>
        </div>
        <div class="col-xl-4">
          <br>
          <div class="text-center">
            <img src='{% static 'img/camera.png' %}' class="text-center">
          </div>
          <p class="lead text-center" id="judul_tabel"> Photographer </p>
          <br>
          <p class="text-center">I really like to take street photography, where you can suddenly meet rare moments.</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> My gear:</p>
          <p class="text text-center">Sony A7RIII, Fujifilm XT10, Canonet</p>
          <br>
          <br>
          <br>
          <p class="lead text-center" id="judul_tabel"> Photographer stats: </p>
          <p class="text-center"> 6 years experience<br>10 short clases<br>100+ awards
        </div>
      </div>
    </div>
  </section>
  <!-- ini akhir tabel -->

  <!-- ini awal headline buat projects -->
  <div class="jumbotron text-center">
    <h1 class="text-center"> My Recent Works </h1>
    <p> Here are a few recent design and photo projects. Want to see more? <a href="mailto:mirfanamrullah@gmail.com?Subject=Hello%20again">Email me</a>.</p>
  </div>
  <!-- ini akhirnya -->

  <!-- ini buat thumbnail -->
  <section class="ini thumbnail">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
          <img src="{% static "img/1_FtYgYG_G6rplUmF5fLzuXA.png" %}" alt="Gitlab" class="img-thumbnail">
        </div>
        <div class="col-xl-4">
          <img src="{% static "img/behance-logo-black.png" %}" alt="behance" class="img-thumbnail">
        </div>
        <div class="col-xl-4">
          <img src="{% static "img/Logo_Viewbug_4.png" %}" alt="Viewbug" class="img-thumbnail">
        </div>
      </div>
    </div>
  </section>
  <!-- ini akhirnya -->

  <!-- tombol daftar -->
  <section class="Register">
    <br>
    <div="container">
      <a href='{% url 'lab_4:message' %}'>
        <button type="button" class="btn btn-primary btn-lg btn-block">Daftar Menjadi Teman</button>
      </a>
    </div>
    <br>
  </section>
  <!-- akhirnya -->

  <!-- ini awal profile -->
  <section class = "profile">
    <div class="jumbotron">
      <h1 class="text-center"> Profile </h1>
      <div class="text-center">
        <img src="{% static "img/_DSC2697.jpg" %}" class="rounded-circle" alt="Irfan">
      </div>
      <h2 class="text-center"> Muhammad Irfan Amrullah </h2>
      <p class="text-center"> The youngest programmer in South East Asia,
Pulitzer Awards 2018. </p>
    </div>
  </section>

  <!-- ini akhir profile -->

{% endblock %}

lab_4/templates/listJadwal.html
{% extends "temp.html" %}
{% load static %}

{% block title %}
<title>Irfan | Create Schedule </title>
{% endblock %}

{%block content %}
    <!-- ini navbar -->
    <nav class="navbar navbar-light bg-transparent">
      <div class = "container">
        <a class="navbar-brand" href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/download.png" %}" width="50" height="50" alt="">
        </a>
        <a href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/close.png" %}" width="50" height="50" alt="">
        </a>
      </div>
    </nav>
    <!-- akhir dari navbar -->

    <!-- last jumbotron -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
          <h1 class="display-4 text-center">List of Schedule!</h1>
        </div>
      </div>
    </section>
    <!-- akhir jumbotron -->

    <!-- ini start form -->
    <section class="container">
      <div class="container">
        <div class ="row">
          {% for i in project %}
            <div class ="col-sm-4 text-center">
              <h2> {{i.title}}</h2>
              <p> {{i.day}} </p>
              <p> {{i.created_date.date}}</p>
              <p> {{i.place}} </p>
              <p> {{i.category}} </p>
              <p> {{i.desc}}</p>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- ini akhir form -->

    <section class="tomboldelete">
      <div class="container text-center">
        <a href='{% url 'lab_4:delete_table' %}'>
          <button type="button" class="btn btn-outline-warning btn-lg">Delete Schedule</button>
        </a>
      </div>
    </section>

    <!-- ini waste of space -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
        </div>
      </div>
    </section>
    <!-- ini akhir waste of space -->


{% endblock %}

lab_4/templates/register.html
{% extends "temp.html" %}
{% load static %}

{% block title %}
<title>Irfan | Register </title>
{% endblock %}

{%block content %}
    <!-- ini navbar -->
    <nav class="navbar navbar-light bg-transparent">
      <div class = "container">
        <a class="navbar-brand" href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/download.png" %}" width="50" height="50" alt="">
        </a>
        <a href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/close.png" %}" width="50" height="50" alt="">
        </a>
      </div>
    </nav>
    <!-- akhir dari navbar -->

    <!-- last jumbotron -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
          <h1 class="display-4 text-center">Let's be friends!<br>I'll email every project to you guys every month!</h1>
        </div>
      </div>
    </section>
    <!-- akhir jumbotron -->

    <!-- ini start form -->
    <section class="form">
      <div class="container">
        <form>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputname">Name</label>
              <input type="text" class="form-control" id="inputname" placeholder="Name">
            </div>
            <div class="form-group col-md-6">
              <label for="inputdates">Birthday</label>
              <input type="date" class="form-control" id="inputdates">
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col">
              <label for="inputEmail">Email</label>
              <input type="email" class="form-control" id="inputEmail" placeholder="Email">
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="inputUser">Username</label>
              <input type="text" class="form-control" id="inputUser" placeholder="Username">
            </div>
            <div class="form-group col-md-4">
              <label for="inputPass">Password</label>
              <input type="password" class="form-control" id="inputPass" placeholder="Password">
            </div>
            <div class="form-group col-md-4">
              <label for="ConfirmPass">Password Confirmation</label>
              <input type="password" class="form-control" id="ConfirmPass" placeholder="Confirm Password">
            </div>
          </div>
        </form>
      </div>
      <div class="container text-center">
        <button type="submit" class="btn btn-outline-warning btn-lg">Submit</button>
      </div>
    </section>
    <!-- ini akhir form -->

    <!-- ini waste of space -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
        </div>
      </div>
    </section>
    <!-- ini akhir waste of space -->


{% endblock %}

lab_4/templates/sayhello.html
{% extends "temp.html" %}
{% load static %}

{% block title %}
<title>Irfan | contact </title>
{% endblock %}

{%block content %}
    <!-- ini navbar -->
    <nav class="navbar navbar-light bg-transparent">
      <div class = "container">
        <a class="navbar-brand" href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/download.png" %}" width="50" height="50" alt="">
        </a>
        <a href='{% url 'lab_4:home' %}'>
          <img src="{% static "img/close.png" %}" width="50" height="50" alt="">
        </a>
      </div>
    </nav>
    <!-- akhir dari navbar -->



    <!-- ini gambar -->
    <section class="profilehello">
      <div class="text-center">
        <img src="{% static "img/atomix_user2.png" %}">
      </div>
    </section>
    <!-- ini akhir dari gambar -->

    <!-- last jumbotron -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
          <h1 class="display-4 text-center">Thanks for taking the time to reach out. <br>What can I do for you today?</h1>
        </div>
      </div>
    </section>
    <!-- akhir jumbotron -->


    <!-- ini start form -->
    <section class="form">
      <div class="container">
        <form>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputname">Name</label>
              <input type="text" class="form-control" id="inputname" placeholder="Name">
            </div>
          <div class="form-group col-md-6">
              <label for="inputEmail">Email</label>
              <input type="email" class="form-control" id="inputEmail" placeholder="Email">
            </div>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Message</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="7" placeholder="Message"></textarea>
          </div>
        </form>
      </div>
      <div class="container text-center">
        <button type="submit" class="btn btn-outline-warning btn-lg">Submit</button>
      </div>
    </section>
    <!-- ini akhir form -->

    <!-- ini waste of space -->
    <section class="helpJumbotron">
      <div class="jumbotron jumbotron-fluid bg-transparent">
        <div class="container">
        </div>
      </div>
    </section>
    <!-- ini akhir waste of space -->

{% endblock %}

lab_4/templates/temp.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
{% block title %}
{% endblock %}
</head>

<body>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

</html>